/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AgentRegistry {
  export type AgentStruct = {
    id: BigNumberish;
    name: string;
    description: string;
    endpoint: string;
    capabilities: string[];
    owner: AddressLike;
    isActive: boolean;
    createdAt: BigNumberish;
  };

  export type AgentStructOutput = [
    id: bigint,
    name: string,
    description: string,
    endpoint: string,
    capabilities: string[],
    owner: string,
    isActive: boolean,
    createdAt: bigint
  ] & {
    id: bigint;
    name: string;
    description: string;
    endpoint: string;
    capabilities: string[];
    owner: string;
    isActive: boolean;
    createdAt: bigint;
  };
}

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivateAgent"
      | "getActiveAgents"
      | "getAgentById"
      | "getAgentsByOwner"
      | "getAllAgents"
      | "getTotalAgents"
      | "registerAgent"
      | "updateAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeactivated"
      | "AgentRegistered"
      | "AgentUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivateAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentsByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgent",
    values: [BigNumberish, string, string, string, string[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgent",
    data: BytesLike
  ): Result;
}

export namespace AgentDeactivatedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [id: BigNumberish, name: string, owner: AddressLike];
  export type OutputTuple = [id: bigint, name: string, owner: string];
  export interface OutputObject {
    id: bigint;
    name: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [id: BigNumberish, name: string];
  export type OutputTuple = [id: bigint, name: string];
  export interface OutputObject {
    id: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivateAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveAgents: TypedContractMethod<
    [],
    [AgentRegistry.AgentStructOutput[]],
    "view"
  >;

  getAgentById: TypedContractMethod<
    [agentId: BigNumberish],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;

  getAgentsByOwner: TypedContractMethod<
    [owner: AddressLike],
    [AgentRegistry.AgentStructOutput[]],
    "view"
  >;

  getAllAgents: TypedContractMethod<
    [],
    [AgentRegistry.AgentStructOutput[]],
    "view"
  >;

  getTotalAgents: TypedContractMethod<[], [bigint], "view">;

  registerAgent: TypedContractMethod<
    [
      name: string,
      description: string,
      endpoint: string,
      capabilities: string[]
    ],
    [bigint],
    "nonpayable"
  >;

  updateAgent: TypedContractMethod<
    [
      agentId: BigNumberish,
      name: string,
      description: string,
      endpoint: string,
      capabilities: string[]
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivateAgent"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveAgents"
  ): TypedContractMethod<[], [AgentRegistry.AgentStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getAgentById"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentsByOwner"
  ): TypedContractMethod<
    [owner: AddressLike],
    [AgentRegistry.AgentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllAgents"
  ): TypedContractMethod<[], [AgentRegistry.AgentStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getTotalAgents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      name: string,
      description: string,
      endpoint: string,
      capabilities: string[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateAgent"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      name: string,
      description: string,
      endpoint: string,
      capabilities: string[]
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentDeactivated"
  ): TypedContractEvent<
    AgentDeactivatedEvent.InputTuple,
    AgentDeactivatedEvent.OutputTuple,
    AgentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentDeactivated(uint256)": TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;
    AgentDeactivated: TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;

    "AgentRegistered(uint256,string,address)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentUpdated(uint256,string)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
  };
}
